### PR TITLE
[MIST-1051] Fix returning null Task

### LINKED ISSUE #1051: MistMaster returns null Task
When allocating tasks to submitted queries, MistMaster returns null Task. We should fix it.

### PR DESCRIPTION
**Pull request by taegeonum**
This PR resolves #1051 
* by creating `isReady` method in Mist client and waiting until MistMaster is ready to receive query submission

### CODE REVIEW

File: mist-client/src/main/java/edu/snu/mist/client/MISTDefaultExecutionEnvironmentImpl.java [hunk 1]
```diff
@@ -53,6 +53,8 @@
    */
   private final Map<String, Tuple<NettyTransceiver, ClientToTaskMessage>> taskConnectionMap;
 
+  private final AtomicBoolean isMasterReady;
```
Comment (DifferentSC) [inline mist-client/src/main/java/edu/snu/mist/client/MISTDefaultExecutionEnvironmentImpl.java]: Add comments on this variable.

**Comment by DifferentSC** [comment]
LGTM. I will merge this.
