### PR TITLE
[MIST-1083] Fix infinite load

### LINKED ISSUE #1083: Fix infinite load
Sometimes the load of event processor becomes infinite. We should fix it.

### PR DESCRIPTION
**Pull request by taegeonum**
This PR resolves #1083

### CODE REVIEW

File: mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/UtilizationLoadUpdater.java [hunk 1]
```diff
@@ -109,17 +112,22 @@ private void updateGroupAndThreadLoad(final EventProcessor eventProcessor,
...
-      } else {
+      }  else {
         // processed event, incoming event
         final double inputRate = (incomingEvent * 1000) / (double) elapsedTime;
         final double processingRate = (processingEvent * 1000000000) / (double) processingEventTime;
-        final double groupLoad = inputRate / processingRate;
-        load = groupLoad;
+
+        if (processingEvent == 0 || processingRate == 0) {
+          load = (1 * 1000000000) / (double) processingEventTime;
```
Comment (DifferentSC) [inline mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/UtilizationLoadUpdater.java]: Change the time unit into static variable.
