### PR TITLE
[MIST-1000] Fix bug in load updater

### LINKED ISSUE #1000: Fix bug in load updater
We found that the load of group becomes infinite. We need to fix it.

### PR DESCRIPTION
**Pull request by taegeonum**
This PR resolves #1000

### CODE REVIEW

File: mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/UtilizationLoadUpdater.java [hunk 1]
```diff
@@ -40,22 +41,26 @@
    */
   private final GroupAllocationTable groupAllocationTable;
 
+  private long startTime;
```
Comment (DifferentSC) [inline mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/UtilizationLoadUpdater.java]: Could you add comments on these variables?

**Comment by DifferentSC** [comment]
Test passed on my machine. Merged.
