### PR TITLE
[MIST-1157] NullPointerException in QueryAllocationManager

### LINKED ISSUE #1157: NullPointerException in ApplicationAwareQueryAllocationManager
The NullPointerException occurs in this situation
* start with two mist tasks
* one mist task is deleted for scaling in 
* when I submit queries after the scaling in, the exception occurs. 

```
java.lang.NullPointerException
        at edu.snu.mist.core.master.lb.allocation.ApplicationAwareQueryAllocationManager.getRandomTask(ApplicationAwareQueryAllocationManager.java:84)
        at edu.snu.mist.core.master.lb.allocation.ApplicationAwareQueryAllocationManager.getAllocatedTask(ApplicationAwareQueryAllocationManager.java:119)
        at edu.snu.mist.core.rpc.DefaultClientToMasterMessageImpl.getQuerySubmitInfo(DefaultClientToMasterMessageImpl.java:91)
        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.avro.ipc.specific.SpecificResponder.respond(SpecificResponder.java:91)
        at org.apache.avro.ipc.Responder.respond(Responder.java:151)
        at org.apache.avro.ipc.NettyServer$NettyServerAvroHandler.messageReceived(NettyServer.java:188)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.apache.avro.ipc.NettyServer$NettyServerAvroHandler.handleUpstream(NettyServer.java:173)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:787)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:555)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by DifferentSC**
This PR closes #1157 via
* Fix `NullPointerException` in ApplicationAwareQueryAllocationManager by adopting global read/write lock.
* Update `AppTaskInfoMap` up-to-date.

### CODE REVIEW

File: mist-core/src/main/java/edu/snu/mist/core/master/lb/allocation/ApplicationAwareQueryAllocationManager.java [hunk 1]
```diff
@@ -101,36 +100,38 @@ private String getRandomTask(final List<String> allTaskList) {
...
+                  appTaskListMap.addTaskToApp(appId, taskCandidate);
+                  return taskAddressInfoMap.getClientToTaskAddress(taskCandidate);
+                }
+              }
             }
+            return taskAddressInfoMap.getClientToTaskAddress(selectedTask);
           }
-        }
-        return taskAddressInfoMap.getClientToTaskAddress(selectedTask);
+      } catch (final Exception e) {
```
Comment (taegeonum) [inline mist-core/src/main/java/edu/snu/mist/core/master/lb/allocation/ApplicationAwareQueryAllocationManager.java]: Where does this exception can occur? it would be good to reduce the area of `try{ ...}` clause.

File: mist-core/src/main/java/edu/snu/mist/core/master/recovery/RecoveryStarter.java [hunk 2]
```diff
@@ -60,16 +61,20 @@ public RecoveryStarter(final Map<String, GroupStats> failedGroupMap,
...
+        // If recovery scheduler is null, it does not request a new task.
+        taskRequestor.setupTaskAndConn(1);
+      }
+      // Start recovering of the queries...
+      recoveryScheduler.startRecovery(failedGroupMap);
+      final long startTime = System.currentTimeMillis();
+      // Blocks the thread until the recovery has been finished...
+      recoveryScheduler.awaitUntilRecoveryFinish();
+      LOG.log(Level.INFO, "Recovery is finished in {0} ms...", System.currentTimeMillis() - startTime);
+    } catch (final AvroRemoteException | InterruptedException e) {
```
Comment (taegeonum) [inline mist-core/src/main/java/edu/snu/mist/core/master/recovery/RecoveryStarter.java]: Where does this exception can occur? it would be good to reduce the area of `try{ ...}` clause.

File: mist-core/src/main/java/edu/snu/mist/core/master/lb/scaling/RecoveryBasedScaleInManager.java [hunk 3]
```diff
@@ -82,10 +106,15 @@ private String getMinimumLoadTask() {
   @Override
   public boolean scaleIn() throws AvroRemoteException, InterruptedException {
     final String removedTaskId = getMinimumLoadTask();
+    // Remove task information firstly.
```
Comment (taegeonum) [inline mist-core/src/main/java/edu/snu/mist/core/master/lb/scaling/RecoveryBasedScaleInManager.java]: Don't we have to hold lock?

File: mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java [hunk 4]
```diff
@@ -105,6 +114,7 @@ public synchronized Void notifyFailedTask(final String taskId) {
     final TaskStats taskStats = taskStatsMap.removeTask(taskId);
     taskAddressInfoMap.remove(taskId);
```
Comment (taegeonum) [inline mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java]: Don't we need lock?
