### PR TITLE
[MIST-1166] Handling recovery with no failed groups

### LINKED ISSUE #1166: Recovery process is stuck with no recovered groups
In `RecoveryScheduler`, when `startRecovery()` is called with no failed groups to recover, `awaitUntilRecoveryFinish()` is not signaled and thus any more recovery process cannot be performed.

We need to fix this problem.

### PR DESCRIPTION
**Pull request by DifferentSC**
This PR closes #1166 via

* Set conditional variable when there is no failed groups in `RecoveryScheduler`.

### CODE REVIEW

File: mist-core/src/main/java/edu/snu/mist/core/master/recovery/DistributedRecoveryScheduler.java [hunk 1]
```diff
@@ -103,6 +103,14 @@ public synchronized void startRecovery(final Map<String, GroupStats> failedGroup
       throw new IllegalStateException("Internal Error : startRecovery() is called while other recovery process is " +
           "already running!");
     }
+    if (failedGroups.isEmpty()) {
+      // Release the possibly awaiting thread when the failed groups are empty.
+      lock.lock();
+      isRecoveryOngoing.set(true);
```
Comment (taegeonum) [inline mist-core/src/main/java/edu/snu/mist/core/master/recovery/DistributedRecoveryScheduler.java]: why is it true?

**Comment by taegeonum** [comment]
LGTM. I'm merging it
